---
- name: Configurando Bucket S3
  hosts: localhost

  tasks:
    - name: Bucket S3
      amazon.aws.s3_bucket:
        name: Devops-FMR
        state: present

    - name: Copiando Arquivos
      community.aws.s3_sync:
        bucket: Devops-FMR
        file_root: frontend/out
        permission: public-read
